### PR TITLE
Added Devsex as it is really needed to identify vimself and my keyboard

### PR DESCRIPTION
**Pull request by keepthebrain**
There is at least dozen of us who find that Devsex missing from this list is offending, and we feel excluded and triggered by this.
So in an attempt to rectify this, I have taken it upon myself to correct this mistake you have, vim believe unintentionally made.

### CODE REVIEW

**Comment by nemanjan00** [comment]
Why are you prejudice to emacs users? So sad... 

And you bloody programmers say you are non-judgmental :(

**Comment by keepthebrain** [comment]
@nemanjan00  Please, don't make assumptions that devsexual and macsexual are same things.

**Comment by nemanjan00** [comment]
Did you just assume my os?

**Comment by keepthebrain** [comment]
@nemanjan00 iDid

**Pull request closed without merging**
